// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webbshop2.Data;

namespace webbshop2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220105212124_Initials")]
    partial class Initials
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("webbshop2.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hammare",
                            Price = 100f,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 2,
                            Name = "Borrmaskin",
                            Price = 2000f,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 3,
                            Name = "Såg",
                            Price = 300f,
                            Quantity = 120
                        },
                        new
                        {
                            Id = 4,
                            Name = "Skruvmejsel",
                            Price = 250f,
                            Quantity = 300
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
